### ISSUE TITLE
LNK1181: Cannot open input file 'opencv_world310.lib'

### ISSUE THREAD

**Issue by mrG7** [SteamyThePunk/OpenCVProject#1]
Failed to produce OpenCV.dll
The command 

\OpenCVProject.uproject" -rocket -waitmutex" exited wirh code-1

As of Unreal Engine 4.10.4

**Comment by SteamyThePunk** [comment]
Please consult: OpenCVProject\ThirdParty\OpenCV\Libraries\x64\ReadMe.txt

You will have to download the OpenCV library files and place them in the containing folder to build the project. The library files are significant in size, and easily acquired so were not directly included in the git repository.
